### ISSUE TITLE
Small Betweenlands + Real First Person 2 Fix Request

### ISSUE THREAD

**Issue by ghost** [sam-kirby/drafty-kites#2]
Firstly, I know this isn't at all the intention of the mod, but I thought I'd at least give it a try considering the activity of both mods' devs with something like this and this is the only mod that I found that could remotely manifest an answer.   The Volarkite when using Betweenlands with Real First Person 2 renders the player's head in first person and obstructs the view and I wanted to know if there's any possibility of getting some sort of fix for this?  I have no idea how hard this would be to do but again, I thought it'd be worth a shot to request.

Thanks in advance!
![image](https://user-images.githubusercontent.com/52370288/102516477-de8ec700-405c-11eb-95d6-f941602d0d3e.png)

**Comment by sam-kirby** [comment]
This is well outside of the scope of this mod, sorry.

The Betweenlands devs do still appear to be active, with the last commit being just over a month ago, and they have responded to issues much more recently.. It's possible they've just been a little busy recently, and will get back to mod development soon.

I'd not previously heard of Real First Person 2.

**Comment by ghost** [comment]
Ah well I figured.  At the very least, thanks for the response!
